# RHEL10 family bios vars
iso_name     = "debian-13.2-amd64-netinst.iso"
iso_checksum = "none"
boot_cmd     = "<esc><wait5>auto net.ifnames=0 biosdevname=0 url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/debian-preseed.cfg<enter><wait10>boot<enter>"
boot_type    = "seabios"
cpu_sockets  = "1"
cpu_core     = "2"
cpu_type     = "host"
memory       = "2048"
os_arch      = "amd64"
os_flavour   = "Debian"
os_major     = "13"
os_minor     = "2"
vm_id        = "3131" # Debian 3 - 13 OS version - 1 Bios
vm_pool      = "debian_pool"
tags         = "debian;debian13"
