# RHEL9 family efi vars

iso_type        = "minimal.iso"
iso_checksum    = "none"
boot_cmd        = "e<down><down><end><bs><bs><bs><bs><bs>inst.text inst.nompath inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/8-efi-ks.cfg<leftCtrlOn>x<leftCtrlOff>"
boot_type       = "ovmf"
bootloader_type = "EFI"
cpu_sockets     = "1"
cpu_core        = "2"
cpu_type        = "host"
memory          = "2048"
os_flavour      = "Rocky"
os_major        = "8"
os_minor        = "10"
vm_pool         = "el8_pool"
tags            = "redhat;rocky8"
